import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  BookOpenCheck,
  Brain,
  BrainCircuit,
  Calendar,
  CheckCircle,
  Code,
  Edit,
  FileText,
  History,
  Info,
  LayoutDashboard,
  MessageSquare,
  Receipt,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  Loader2,
  Tag,
  HelpCircle,
} from 'lucide-react';

export const Icons = {
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  bookOpenCheck: BookOpenCheck,
  brain: Brain,
  brainCircuit: BrainCircuit,
  calendar: Calendar,
  checkCircle: CheckCircle,
  code: Code,
  edit: Edit,
  fileText: FileText,
  history: History,
  info: Info,
  layoutDashboard: LayoutDashboard,
  messageSquare: MessageSquare,
  receipt: Receipt,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  shieldCheck: ShieldCheck,
  spinner: Loader2,
  tag: Tag,
  help: HelpCircle,
};
